### ISSUE TITLE
Add 11ty

### ISSUE THREAD

**Issue by DirtyF** [staystatic/staystatic#10]
@11ty could be with Liquid, Nunjucks or [any of the other supported templating engines](https://github.com/11ty/eleventy#eleventy-)

**Comment by geraldb** [comment]
@DirtyF  Always love new samples and web compiler.  Pick the template language you prefer (or build two or three samples :-).   If you need any assistance / help to get started, just let me know.

If you contribute - you're more than welcome to join the stay static org (to make it easier) - just let me know and I send you an inviation (via GitHub).

**Comment by DirtyF** [comment]
@geraldb I'll try to give it a shot.

Not related: What about adding some topics to this repo to make it more discoverable on GitHub?

**Comment by geraldb** [comment]
@DirtyF Good point / idea - I added all website compiler (that have samples) - if want to see more added just tell me and I add more.

Please, do. Would be great to welcome 11ty. Greeting from Vienna. Cheers. Prost.
