### ISSUE TITLE
new cuttlebelle static site does not compile as demo

### ISSUE THREAD

**Issue by orenmizr** [staystatic/staystatic#13]
hi @dominikwilkowski : 
content is not shown. seem broken. 
win10 + node 8, run all npm commands including install. server opens up - and the html is not at all close. 

update: do you have anything in there that is mac\linux specific - in most cases that is the issue.

**Comment by dominikwilkowski** [comment]
hi @orenmizr 

I can't reproduce. Can you tell me more what happens? What node version you're using etc.

```shell
$ cd staystatic/cuttlebelle
$ npm install
> fsevents@1.1.3 install /Users/dominikwilkowski/Sites/staystatic/cuttlebelle/node_modules/fsevents
> node install

[fsevents] Success: "/Users/dominikwilkowski/Sites/staystatic/cuttlebelle/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uws@9.14.0 install /Users/dominikwilkowski/Sites/staystatic/cuttlebelle/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

npm WARN cuttlebelle-staystatic@ No repository field.
npm WARN cuttlebelle-staystatic@ license should be a valid SPDX license expression

added 578 packages in 16.457s
$ npm start

> cuttlebelle-staystatic@ start /Users/dominikwilkowski/Sites/staystatic/cuttlebelle
> cuttlebelle

 🐙           Cuttlebelle v1.0.0-alpha.57
 🔔  INFO:    Generating pages
 🚀           Successfully built 5 pages to site/ in 0.643s

$ 
```

**Comment by orenmizr** [comment]
there are no errors. i get the same success alert. 
but the result is this (i removed links section while debugging) 
![GitHub Logo](https://i.imgur.com/AiDUOP3.png)

**Comment by dominikwilkowski** [comment]
I'm sorry; this must be frustrating.
I still can't reproduce this so to help me find the issue can you please answer some of the questions below:

- What os are you using
- What node version
- Can you past in your ci output here after running `npm start`
- Can you add a zip of your `site/` folder please?

Thank you

**Comment by orenmizr** [comment]
ndoe v8.11.1 + npm 5.6.0 + cuttlebelle 57 on a windows 10 machine
- cloned staystatic
- cd cuttlebelle
- npm install
- npm run build OR npm start

```
> cuttlebelle-staystatic@ start C:\Git\staystatic\cuttlebelle
> cuttlebelle

 🐙           Cuttlebelle v1.0.0-alpha.57
 🔔  INFO:    Generating pages
 🚀           Successfully built 5 pages to site/ in 0.534s
```

same result as before. try running it on a window VM. 
zipped site folder: https://expirebox.com/download/f0ab8c630360891d980362346f398946.html

**Comment by dominikwilkowski** [comment]
The zip doesn't work. Can you send it to me hi@dominik-wilkowski.com
Thanks

**Comment by orenmizr** [comment]
checked it on ubuntu (on win10) - same result. also cuttlebelle actual website repo yields same messed up htmls.

**Comment by dominikwilkowski** [comment]
Sorry I can't reproduce at all. Tried a bunch of machines and VMs on my side. Anyone else able to reproduce?

**Comment by dominikwilkowski** [comment]
moved to cuttlebelle/cuttlebelle#33
