### ISSUE TITLE
Pelican

### ISSUE THREAD

**Issue by matbrgz** [staystatic/staystatic#14]
https://blog.getpelican.com

written in Python + Jinja templates

**Comment by geraldb** [comment]
You're welcome to add the sample. If you need help to get started let me know. Greetings from Vienna. Cheers.

**Comment by matbrgz** [comment]
How could I start?

**Comment by geraldb** [comment]
Look at a sample that is close to Python (maybe the Nunjucks templates? in Metalsmith - Nunjucks is like Jinja).  You can find a starter kit @ <https://github.com/staystatic/staystatic-starter> for the style (css) and the markdown posts and the datafile for bookmarks / links.
