### ISSUE TITLE
Build a beanchmark tool

### ISSUE THREAD

**Issue by matbrgz** [staystatic/staystatic#16]
Iss possible use this repo to create a way to do that?

At this moment there are none benchmark mensuring many SSG's.

**Comment by geraldb** [comment]
Everything is possible.

**Comment by geraldb** [comment]
Please, only post / open issues if you want to contribute. This issue tracker is not a chat service. Thanks for your understanding.

**Comment by matbrgz** [comment]
I understand that this is not a chat service and I do not intend to use it for that, my intentions are purely at the discretion of discussion and with the intention of opening a pull request.
Considering that the compilation time between the SGGs can vary and that science needs an open standard of categorization of data, experiments and benchmarking will be performed evaluating the static site generators in the compilation time period and verifying the behavior with 1000, 100000, 1000000 records of 10kb and 100kb. This will be able to discuss the operation of static site generators, the data categorization method used by these platforms and how this technology can benefit teaching by developing a tool for creating websites for teachers.
Do you think this test will work? I accept contributions.
