### ISSUE TITLE
Updating Metalsmith-in-place

### ISSUE THREAD

**Issue by wernerglinka** [staystatic/staystatic#5]
Hi Gerald,
I have been using your static site as a testbed for Metalsmith explorations and have learned a lot. I just updated the metalsmith-in-place plugin to version 2.0.1  and ""all hell broke loose" ;-)

Now the build process is interrupted with an "Error: invalid engine, the engine should be a constructor."

Would you have an idea what is causing this? 
Best regards,
Werner

PS Ich habe nicht gewusst das du aus Osterreich bist, da hätte ich aus Deutsch schreiben können. Ich bin in den US im kalten Minnesota ;-)

**Comment by geraldb** [comment]
Greetings from Vienna. Sorry, I'm not a Methalsmith expert (was about two years ago when I created the sample).  Best to ask in the official forum / mailing list if it exists or open an issue on the metalsmith engine or plugin. Good luck. Thanks for your interest in the Stay Static Samples.

**Comment by wernerglinka** [comment]
Hi Gerald and greetings from sunny but very cold Minneapolis,
Thank you for your response. I figured out what is happening. I posted the solution here if your are interested: https://github.com/wernerglinka/ms-in-place-nunjucks <https://github.com/wernerglinka/ms-in-place-nunjucks>

Best,
Werner
