### ISSUE TITLE
What about removing image preview

### ISSUE THREAD

**Issue by MoOx** [staystatic/staystatic#8]
They are all the same, I don't see the point :)

What about technologies logo? (or nothing but text)

**Comment by geraldb** [comment]
Good point. The inspirtation is / was the ToDoMVC showcase <http://todomvc.com> and the HackerNews PWA showcase <https://hnpwa.com/>.

Big fan of text. Yeah, nothing but text to keep it simple. Why not.  

One more idea / plan was to add (github) avatar(s) of the contributors (for the sample) to encourage contribution. Will try to get it done / started this week.

**Comment by MoOx** [comment]
I like your idea :)

**Comment by MoOx** [comment]
See https://github.com/staystatic/staystatic.github.io/pull/2
